spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/pepperfry
     username: root
     password: Anil
  jpa:
    show-sql: false
    generate-ddl: true
product:
 name: AppleMacbookSeries
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: false
server:
  port: 8085
